import React from 'react';

const PrivacyPolicy: React.FC = () => {
    return (
        <div className="bg-[#F2F6FB]">
            <div className='bg-white p-24 mx-40 my-20'>
                <h1 className="text-4xl font-light text-left mb-6 text-[#8D1B3D]">Privacy Policy</h1>
                <div className="text-lg">
                    <p className="mb-4 font-light text-lg text-zinc-700">
                        The Website and Application are operated and run by Zamtar Tech Private Limited, a private limited incorporated under the provisions of Companies Act 2013 and having its registered address at “H544, SEC-49, FARIDABAD Faridabad, Haryana, 121001” represented by its Directors and hereinafter referred to as the “Company” (where such expression shall, unless repugnant to the context thereof, be deemed to include its respective legal heirs, representatives, administrators, permitted successors and assigns) are operating the Website and the Mobile Application on the Brand Name “Gatoes”.
                    </p>
                    <p className="mb-4 font-light text-lg text-zinc-700">
                        This legal agreement is an electronic record in terms of Indian Information Technology Act, 2000 and rules there under as applicable and the amended provisions about electronic records in various statutes as amended by the Indian Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                    </p>
                    <p className="mb-4 font-light text-lg text-zinc-700" >This legal document is published in accordance with the provisions of Rule 3 (1) of the Indian Information Technology (Intermediaries guidelines) Rules, 2011 and Rule 4 of the Information Technology (Reasonable security practices and procedures and sensitive personal data or information) Rules, 2011 of Information Technology Act, 2000 amended through Information Technology Amendment Act, 2008 that require publishing the Terms and practices for access or usage of the Platform.

                    </p>
                    <p className='mb-4 font-light text-lg text-zinc-700'>The creator of these Terms ensures steady commitment to Your usage of the Platform with regard to the protection of your invaluable information. This document contains information about the Website “www.gatoes.com” and Mobile Application “Gatoes” (hereinafter collectively referred to as the “Platform”).

                    </p>

                    <p className='mb-4 font-light text-lg text-zinc-700'>To provide You with Our uninterrupted use of the Platform, We may collect and, in some circumstances, disclose information about you with your permission. To ensure better protection of Your privacy, We provide this notice explaining Our information collection and disclosure policies, and the choices You make about the way Your information is collected and used.

                    </p>
                    <p className='mb-4 font-light text-lg text-zinc-700'>This Privacy Policy shall be in compliance with the General Data Protection Regulation (GDPR) in effect from May 25, 2018, and any and all provisions that may read to the contrary shall be deemed to be void and unenforceable as of that date. If you do not agree with the terms and conditions of our Privacy Policy, including in relation to the manner of collection or use of your information, please do not use or access the Site. If you have any questions or concerns regarding this Privacy Policy, you should contact our Customer Support Desk at info@gatoes.com.

                    </p>

                    <h2 className="text-xl font-light text-zinc-700 mt-6 uppercase">INFORMATION WE COLLECT</h2>
                    <p className="font-light text-lg text-zinc-700 mr-12 pb-4" >We are committed to respecting Your online privacy. We further recognize Your need for appropriate protection and management of any Personal Information You share with us. We may collect the following information:</p>


                    <p className="font-light text-lg ml-12 text-zinc-700">
                        Personal data such as, but not limited to, Name, Email Id, Mobile Number, etc;<br></br>Information collected through the device permissions including but not limited to Device Location, Contacts permission, Calling action permission, read-text permission and notification permission.<br></br>Tracking Information such as, but not limited to the IP address of your device and Device ID when connected to the Internet. This information may include the URL that you just came from (whether this URL is on the Platform or not), which URL you next go to (whether this URL is on the Platform or not), your computer or device browser information, and other information associated with your interaction with the Platform;<br></br>Details of Platform usage for analytics.
                    </p>
                    <p className=" font-light text-lg mr-12 text-zinc-700 pb-4">This privacy policy also applies to data we collect from users who are not registered as members of this Platform, including, but not limited to, browsing behaviour, pages viewed etc. We also collect and store personal information provided by You from time to time on the Platform. We only collect and use such information from you that we consider necessary for achieving a seamless, efficient and safe experience, customized to your needs including:

                    </p>
                    <p className="font-light text-lg ml-10 text-zinc-700">
                        To enable the viewing of content in your interest.<br></br>To communicate the necessary account-related information from time to time.<br></br>To comply with applicable laws, rules and regulations.
                    </p>
                    <p className=" font-light text-lg mr-12 text-zinc-700 pb-4">The Platform may also use contact information internally to direct its efforts for platform improvement but shall immediately delete all such information upon withdrawal of your consent for the same through the ‘unsubscribe’ button or through an email to be sent to info@gatoes.com</p>


                    <h2 className="text-xl font-light text-zinc-700 mt-6 uppercase">OUR USE OF YOUR INFORMATION</h2>
                    <p className='font-light text-lg text-zinc-700 pb-4'>The information provided by you shall be used to provide accessibility to the platform for you and all users.</p>
                    <p className='font-light text-lg text-zinc-700 ml-12'>For maintaining an internal record.<br></br>For enhancing the platform accessibility provided.
                    </p>
                    <p className='font-light text-lg text-zinc-700 pb-4'>For more details about the nature of such communications, please refer to our Terms. Further, your data and Sensitive Personal data may be collected and stored by Us for internal record. We use Your tracking information such as IP addresses, and or Device ID to help identify you and to gather broad demographic information and make further accessibility available to you. We will not sell, license or trade Your personal information. We will not share your personal information with others unless they are acting under our instructions or we are required to do so by law.</p>
                    <p className='font-light text-lg text-zinc-700'>Information collected via Our server logs includes users' IP addresses and the pages visited; this will be used to manage the web system and troubleshoot problems. We also use third-party analytics, tracking, optimization and targeting tools to understand how users engage with our Platform so that we can improve it and cater personalized content/ads according to their preferences.</p>

                    <h2 className="text-xl font-light text-zinc-700 mt-6 uppercase">HOW INFORMATION IS COLLECTED</h2>
                    <p className='font-light text-lg text-zinc-700 pb-4'>Before or at the time of collecting personal information, we will identify the purposes for which information is being collected. If the same is not identified to you, you have the right to request the Platform to elucidate the purpose of collection of said personal information, pending the fulfilment of which you shall not be mandated to disclose any information whatsoever.

                    </p>
                    <p className='font-light text-lg text-zinc-700 pb-4'>We will collect and use your personal information solely to fulfil those purposes specified by us, within the scope of the consent of the individual concerned or as required by law. We will only retain personal information as long as necessary for the fulfilment of those purposes. We will collect personal information by lawful and fair means and with the knowledge and consent of the individual concerned.

                    </p>
                    <p className='font-light text-lg text-zinc-700'>Personal data should be relevant to the purposes for which it is to be used, and, to the extent necessary for those purposes, should be accurate, complete, and up-to-date.

                    </p>

                    <h2 className="text-xl font-light text-zinc-700 mt-6 uppercase">EXTERNAL LINKS ON THE PLATFORM</h2>
                    <p className='font-light text-lg text-zinc-700'>The Platform may include advertisements, hyperlinks, payment portal links to other Websites or resources. We have no control over any other website or resources or contents available on these other websites, which are provided by companies or persons other than Us. You acknowledge and agree that we are not responsible for the availability of any such external sites or resources, and do not endorse any advertising, or other materials on or available from such platform or resources. You acknowledge and agree that We are not liable for any loss or damage which may be incurred by you as a result of the availability of those external sites or resources, or as a result of any reliance placed by you on the completeness, accuracy or existence of any advertising or other materials on, or available from, such Websites. These external third party websites and resource providers may have their privacy policies governing the collection, storage, retention and disclosure of Your Personal Information that You may be subject to. We recommend that you enter the Website and review their privacy policy.</p>

                    <h2 className="text-xl font-light text-zinc-700 mt-6 uppercase">YOUR RIGHTS</h2>
                    <p className='font-light text-lg text-zinc-700 pb-4'>Unless subject to an exemption, you have the following rights concerning your data:</p>
                    <p className='font-light text-lg text-zinc-700 ml-10'>The right to request a copy of your data which we hold about you.<br></br>The right to request for any correction to any personal data if it is found to be inaccurate or out of date.<br></br>The right to withdraw Your consent to the processing at any time.<br></br>The right to object to the processing of personal data.<br></br>The right to complain about a supervisory authority.<br></br>The right to obtain information as to whether personal data are transferred to a third country or an international organization.</p>

                    <p className='font-light text-lg text-zinc-700'>Where you hold an account, you are entitled to a copy of all personal data which we hold concerning you. You are also entitled to request that we restrict how we use your data in your account when you log in.
                    </p>
                    <h2 className="text-xl font-light text-zinc-700 mt-6 uppercase">CONFIDENTIALITY</h2>
                    <p className='font-light text-lg text-zinc-700'>You further acknowledge that the Platform may contain information which is designated confidential by us and that you shall not disclose such information without our prior written consent. Your information is regarded as confidential and therefore will not be divulged to any third party, unless if legally required to do so to the appropriate authorities. We will not sell, share, or rent your personal information to any third party or use your e-mail address for unsolicited mail. Any emails sent by us will only be in connection with the platform, and you retain sole discretion to seek for discontinuation of such communications at any point of time.</p>

                    <h2 className="text-xl font-light text-zinc-700 mt-6 uppercase">COOKIES</h2>

                    <p className='font-light text-lg text-zinc-700'>We use data collection devices such as “cookies” on certain pages of our Platform. “Cookies” are small files sited on your hard drive that assist us in providing customized services. We also offer certain features that are only available through the use of a “cookie”. Cookies can also help us provide information which is targeted to your interests. Cookies may be used to identify logged in or registered users. Our Platform uses session cookies to ensure that you have a good experience. These cookies contain a unique number, your 'session ID', which allows our server to recognize your computer and 'remember' what you've done on the site. The benefits of this are:</p>
                    <p className='font-light text-lg text-zinc-700 ml-10'>You only need to log in once if you're navigating secure areas of the site<br></br>Our server can distinguish between your computer and other users, so you can see the information that you have requested.</p>
                    <p className='font-light text-lg text-zinc-700 pb-4'>You can choose to accept or decline cookies by modifying your browser settings if you prefer. This may prevent you from taking full advantage of the Platform. We also use various third-party cookies for usage, behavioral, analytics and preferences data. The following are the different types of cookies used on the Platform:

                    </p>


                    <p className='font-light text-lg text-zinc-700 ml-10'>Authentication cookies: To identify the user and share the content that he or she requested.<br></br>Functionality cookies: For the customized user experience and resuming past course progress.<br></br>Tracking, optimization, and targeting cookies: To capture usage metric on the device, operating system, browser, etc. To capture behavioural metrics for better content delivery. To cater and suggest most suited services.</p>
                    <p className='font-light text-lg text-zinc-700'>Pixel tags” (also called beacons or pixels) are small blocks of code installed on (or called by) a webpage, app, or advertisement which can retrieve certain information about your device and browser, including for example device type, operating system, browser type and version, website visited, time of visit, referring website, IP address, and other similar information, including the small text file (the cookie) that uniquely identifies the device. Pixels provide how third parties can set and read browser cookies from a domain that they do not themselves operate and collect information about visitors to that domain, typically with the permission of the domain owner.</p>
                    <h2 className="text-xl font-light text-zinc-700 mt-6 uppercase">GOOGLE ADSENSE</h2>
                    <p className='font-light text-lg text-zinc-700 pb-4'>Google AdSense is a tool that allows website publishers to deliver advertisements to site visitors in exchange for revenue calculated on a per-click or per-impression basis. To do this, Google uses cookies and tracking technology to deliver ads personalized to a website user/visitor. In this regard the following terms are specified to the Users:</p>
                    <p className='font-light text-lg text-zinc-700 ml-10'>Third-party vendors, including Google, use cookies to serve ads based on your prior visits to our website or other websites.<br></br>Google's use of advertising cookies enables us and our partners to serve advertisements to you based on their visit to our Platform and/or other websites on the Internet.<br></br>You may opt-out of personalized advertising by visiting Ads Settings.<br></br>All advertisements of third parties on our Platform are for informative purposes only and neither the Platform nor the Company guarantees or bears liability for the authenticity of the advertisements.<br></br>At no point will the Company permit its Competitors to advertise on the Platform.<br></br>You may visit the links in the advertisements at your own risk or choose to not accept the cookies permitting third parties to display their advertisements.</p>


                    <h2 className="text-xl font-light text-zinc-700 mt-6 uppercase">GOOGLE ANALYTICS</h2>

                    <p className='font-light text-lg text-zinc-700 pb-4'>UWe use Google Analytics to help us to understand how you make use of our content and work out how we can make things better. These cookies follow your progress through us, collecting anonymous data on where you have come from, which pages you visit, and how long you spend on the site. This data is then stored by Google to create reports. These cookies do not store your data.

                    </p>
                    <p className='font-light text-lg text-zinc-700'>The information generated by the cookie about your use of the Website, including your IP address, may be transmitted to and stored by Google on servers in the United States. Google may use this information to evaluate your use of the website, compiling reports on website activity for us and providing other services relating to website activity and internet usage. Google may also transfer this information to third parties where required to do so by law, or where such third parties process the information on Google's behalf. Google will not associate your IP address with any other data held by Google. By using this website, you consent to the processing of data about you by Google in the manner and for the purposes set out above. The Google website contains further information about Analytics and a copy of Google's privacy policy pages</p>


                    <h2 className="text-xl font-light text-zinc-700 mt-6 uppercase">OTHER INFORMATION COLLECTORS
                    </h2>


                    <p className='font-light text-lg text-zinc-700 pb-4'>Except as otherwise expressly included in this Privacy Policy, this document only addresses the use and disclosure of information we collect from you. To the extent that you disclose your information to other parties, whether they are on our Platform or other sites throughout the Internet, different rules may apply to their use or disclosure of the information you disclose to them. To the extent that we use third party advertisers, they adhere to their privacy policies. Since we do not control the privacy policies of the third parties, you are subject to ask questions before you disclose your personal information to others.</p>
                    <p className='font-light text-lg text-zinc-700'>Local storage is a technology that allows a website or application to store information locally on your device. “Software Development Kits” (also called SDKs) function like pixels and cookies, but operate in the mobile app context where pixels and cookies cannot always function. The primary app developer can install pieces of code (the SDK) from partners in the app, and thereby allow the partner to collect certain information about user interaction with the app and information about the user device and network information.
                    </p>
                    <h2 className="text-xl font-light text-zinc-700 mt-6 uppercase">OUR DISCLOSURE OF YOUR INFORMATION</h2>
                    <p className='font-light text-lg text-zinc-700 pb-4'>We may host surveys for survey creators for our platform who are the owners and users of your survey responses. We do not own or sell your responses. Anything you expressly disclose in your responses will be disclosed to survey creators. Please contact the survey creator directly to better understand how they might share your survey responses.
                    </p>
                    <p className='font-light text-lg text-zinc-700 pb-4'>Information collected will not be considered as sensitive if it is freely available and accessible in the public domain or is furnished under the Right to Information Act, 2005, any rules made thereunder or any other law for the time being in force.</p>
                    <p className='font-light text-lg text-zinc-700 py-4'>Due to the existing regulatory environment, we cannot ensure that all of your private communications and other personally identifiable information will never be disclosed in ways not otherwise described in this Privacy Policy. By way of example (without limiting and foregoing), we may be forced to disclose information to the government, law enforcement agencies or third parties. Therefore, although we use industry-standard practices to protect your privacy, we do not promise, and you should not expect, that your personally identifiable information or private communications would always remain private. We do however assure you that any disclosure of your personally identifiable information shall be personally intimated to you through an email sent to your provided email address.</p>
                    <p className='font-light text-lg text-zinc-700'>As a matter of policy, we do not sell or rent any personally identifiable information about you to any third party. However, the following describes some of the ways that your personally identifiable information may be disclosed:</p>
                    <p className='font-light text-lg text-zinc-700'>External Service Providers: There may be several services offered by external service providers that help you use our Platform. If you choose to use these optional services, and in the course of doing so, disclose information to the external service providers, and/or permit them to collect information about you, then their use of your information is governed by their privacy policy.<br></br>Law and Order: We cooperate with law enforcement inquiries, as well as other third parties to enforce laws, such as intellectual property rights, fraud and other rights. We can (and you authorize us to) disclose any information about you to law enforcement and other government officials as we, in our sole discretion, believe necessary or appropriate, in connection with an investigation of fraud, intellectual property infringements, or other activity that is illegal or may expose us or you to legal liability.</p>
                    <h2 className="text-xl font-light text-zinc-700 mt-6 uppercase">ACCESSING, REVIEWING AND CHANGING YOUR PROFILE
                    </h2>
                    <p className='font-light text-lg text-zinc-700'>Following registration, you can review and change the information you submitted at the stage of registration, except Email ID and mobile number. An option for facilitating such change shall be present on the Platform and such change shall be facilitated by the User. If you change any information, we may or may not keep track of your old information. We will not retain in our files information you have requested to remove for certain circumstances, such as to resolve disputes, troubleshoot problems and enforce our terms and conditions. Such prior information shall be completely removed from our databases, including stored ‘back up’ systems. If you believe that any information, we are holding on you is incorrect or incomplete, or to remove your profile so that others cannot view it, the User needs to remediate, and promptly correct any such incorrect information.

                    </p>
                    <h2 className="text-xl font-light text-zinc-700 mt-6 uppercase">CONTROL OF YOUR PASSWORD
                    </h2>
                    <p className='font-light text-lg text-zinc-700'>You are entirely responsible for maintaining the confidentiality of your password. You must protect it against unauthorized access of your account and information by choosing your password carefully and keeping your password and computer secure by signing out after using our Platform. You agree not to use the account, username, email address or password of another Member at any time or to disclose your password to any third party. You are responsible for all actions taken with your login information and password, including fees. If you lose control of your password, you may lose substantial control over your personally identifiable information and may be subject to legally binding actions taken on your behalf. Therefore, if your password has been compromised for any reason, you should immediately change your password. You agree to notify us immediately if you suspect any consistent unauthorized use of your account or access to your password even after changing it.

                        .</p>
                    <h2 className="text-xl font-light text-zinc-700 mt-6 uppercase">SECURITY
                    </h2>
                    <p className='font-light text-lg text-zinc-700 pb-4'>We treat data as an asset that must be protected against loss and unauthorized access. We employ many different security techniques to protect such data from unauthorized access by members inside and outside the Platform. We follow generally accepted industry standards to protect the Personal Information submitted to us and information that we have accessed.

                    </p>
                    <p className='font-light text-lg text-zinc-700'>However, as effective as encryption technology is, no security system is impenetrable. Our Platform cannot guarantee the security of our database, nor can we guarantee that information you provide won’t be intercepted while being transmitted to the Platform over the Internet.



                    </p>
                    <h2 className="text-xl font-light text-zinc-700 mt-6 uppercase">SEVERABILITY
                    </h2>
                    <p className='font-light text-lg text-zinc-700'>Each paragraph of this Privacy Policy shall be and remain separate from and independent of and severable from all and any other paragraphs herein except where otherwise expressly indicated or indicated by the context of the agreement. The decision or declaration that one or more of the paragraphs are null and void shall not affect the remaining paragraphs of this privacy policy.</p>
                    <h2 className="text-xl font-light text-zinc-700 mt-6 uppercase">AMENDMENT</h2>
                    <p className='font-light text-lg text-zinc-700'>Our Privacy Policy may change from time to time. The most current version of the policy will govern our use of your information and will always be at the Platform. Any amendments to this Policy shall be deemed as accepted by the User on their continued use of the Platform.</p>

                    <h2 className="text-xl font-light text-zinc-700 mt-6 uppercase">AMENDMENT</h2>
                    <p className='font-light text-lg text-zinc-700'>As a responsible Platform, we do not use automatic decision-making or profiling.

                    </p>

                    <h2 className="text-xl font-light text-zinc-700 mt-6 uppercase">CONSENT WITHDRAWAL, DATA DOWNLOAD & DATA REMOVAL REQUESTS</h2>

                    <p className='font-light text-lg text-zinc-700'>To withdraw your consent, or to request the download or delete your data with us at any time, please email to company@gatoes.com.</p>
                    <h2 className="text-xl font-light text-zinc-700 mt-6 uppercase">CONTACT</h2>


                    <p className='font-light text-lg text-zinc-700'>If you have any questions or concerns regarding this privacy policy, you should contact us by sending an e-mail to please email to company@gatoes.com. Information provided on the Platform may not be 100% accurate and may be provided for promotional purposes only.</p>

                </div>
            </div>
        </div>
    );
};

export default PrivacyPolicy;
